### ISSUE TITLE
Re-enable Scan_Integration_WebViewSample test in PR build ?

### ISSUE THREAD

**Issue by DaveTryon** [microsoft/axe-windows#912]
## Describe the bug

The `Scan_Integration_WebViewSample` test was consistently failing in the PR build. It works locally, so it appears to be something in the pipeline environment. This tracks the work/decision to re-enable it or just live without it.

**To Reproduce**

1. Revert #913 locally
2. Open a PR
3. Watch the PR fail

## Expected behavior

PR should succeed

## Actual behavior

You get this error message:

```
  Failed Scan_Integration_WebViewSample (True) [15 s]
  Error Message:
   Assert.Fail failed. Exception caught - See details below.
Assert.AreEqual failed. Expected:<21>. Actual:<0>. 
   at Microsoft.VisualStudio.TestTools.UnitTesting.Assert.ThrowAssertFailed(String assertionName, String message)
   at Microsoft.VisualStudio.TestTools.UnitTesting.Assert.AreEqual[T](T expected, T actual, IEqualityComparer`1 comparer, String message, Object[] parameters)
   at Microsoft.VisualStudio.TestTools.UnitTesting.Assert.AreEqual[T](T expected, T actual)
   at Axe.Windows.AutomationTests.AutomationIntegrationTests.ValidateOutput(IReadOnlyCollection`1 output, Int32 expectedErrorCount, Int32 expectedWindowCount) in D:\a\1\s\src\AutomationTests\AutomationIntegrationTests.cs:line 321
   at Axe.Windows.AutomationTests.AutomationIntegrationTests.ScanIntegrationCore(Boolean sync, String testAppPath, Int32 expectedErrorCount, Int32 expectedWindowCount, Nullable`1 processId) in D:\a\1\s\src\AutomationTests\AutomationIntegrationTests.cs:line 286
   at Axe.Windows.AutomationTests.AutomationIntegrationTests.<>c__DisplayClass25_0.<Scan_Integration_WebViewSample>b__0() in D:\a\1\s\src\AutomationTests\AutomationIntegrationTests.cs:line 147
   at Axe.Windows.AutomationTests.TimedExecutionWrapper.<>c__DisplayClass14_0.<CreateThreadForTest>b__0() in D:\a\1\s\src\AutomationTests\TimedExecutionWrapper.cs:line 49
  Stack Trace:
     at Axe.Windows.AutomationTests.AutomationIntegrationTests.RunWithTimedExecutionWrapper(TimeSpan allowedTime, Action testAction) in D:\a\1\s\src\AutomationTests\AutomationIntegrationTests.cs:line 248
   at Axe.Windows.AutomationTests.AutomationIntegrationTests.Scan_Integration_WebViewSample(Boolean sync) in D:\a\1\s\src\AutomationTests\AutomationIntegrationTests.cs:line 145

  Passed Scan_Integration_WebViewSample (False) [11 s]
```

## Desktop (please complete the following information):

 - OS: [e.g. Windows 10 1809] (Get the version by running `winver` from the command line)
 - Accessibility Insights for Windows Version:
 - Target Application: [e.g. Chrome, Wildlife Manager]
 - Target Application Version: [e.g. 22]

## Additional context

I've looked into this, and determined that the WebViewSample app is opening, but it's not rendering the HTML. I've tried loading from a local HTML file, as well as adding an larger timeout in case it's slow network traffic. My opinion is that it's a restriction in the pipeline and that we just live without it.

**Comment by DaveTryon** [comment]
Looking at the backlog, we just need to live with this one
